# Generated by Django 4.2.6 on 2023-10-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AidAuto', '0002_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='user_image',
            field=models.ImageField(null=True, upload_to='Mecanicien'),
        ),
    ]
