# Generated by Django 4.2.6 on 2023-10-15 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AidAuto', '0003_utilisateur_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='profession',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AidAuto.role'),
        ),
    ]
