# Generated by Django 4.2.6 on 2023-10-16 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AidAuto', '0005_alter_contact_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='vehicule',
        ),
    ]
