# Generated by Django 4.2.6 on 2023-10-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AidAuto', '0008_rename_nom_d_utilisateur_register_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=350)),
                ('email', models.EmailField(max_length=350)),
                ('service', models.CharField(choices=[('', 'Test diagnostique'), ('', 'Entretien du moteur'), ('', 'Remplacement des pneus'), ('', "Changement d'huile")], max_length=50)),
                ('Date_reservation', models.DateField()),
                ('Description', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
    ]
