# Generated by Django 4.2.6 on 2023-10-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AidAuto', '0009_booking'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='booking',
        ),
    ]
