# Generated by Django 4.2.6 on 2023-10-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AidAuto', '0010_alter_booking_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('', 'Selectionner un Service'), ('', 'Test diagnostique'), ('', 'Entretien du moteur'), ('', 'Remplacement des pneus'), ('', "Changement d'huile")], max_length=50),
        ),
    ]
