# Generated by Django 4.2.6 on 2023-10-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AidAuto', '0011_alter_booking_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
    ]
